baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "HyperSpy"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["taxonomy"]

markup:
  highlight:
    noClasses: false


params:
  author:
    name: "HyperSpy Development team"
  description: "Landing site for HyperSpy organization."
  images:
    - /images/hyperspy_logo.png
    - /images/pyxem.png
  navbarlogo:
    image: hyperspy_logo.png
    text: HyperSpy
    link: /
  hero:
    title: HyperSpy
    image: hyperspy_logo.png
    buttontext: Get Started
    buttonlink: https://hyperspy.org/hyperspy-doc/current/index.html
  navbar:
    - title: Blog
      url: /blog/
    - title: Documentation
      url: https://hyperspy.org/hyperspy-doc/current/index.html
    - title: Installation
      url: http://hyperspy.org/hyperspy-doc/current/user_guide/install.html
    - title: News
      url: /news/
    - title: Gitter
      url: https://gitter.im/hyperspy/hyperspy
    - title: GitHub
      url: github.com/hyperspy
      icon: github

  keyfeatures:
    features:
      - title: Named and Scaled Axes
        text:  "Two families of named and scaled axes: signal and navigation"
      - title: Visualization
        text:  Visualization tools for multi-dimensional spectra and images.
      - title: Analysis
        text:  Easy access multi-dimensional curve fitting and blind source separation.
      - title: Performance
        text:  Built on top of NumPy, SciPy, matplotlib, dask and scikit-learn for high performance.
      - title: Extensible
        text: Modular design for easy extensibility.
      - title: Community Maintained
        text: The theme is maintained by the [Hyperspy Developers](/about/).

  casestudies:
    title: HyperSpy Ecosystem
    features:
        - img: /images/pyxem.png
          alttext: Logo of Pyxem
          url: https://pyxem.readthedocs.io/en/stable/
        - img: /images/rosettasciio.svg
          alttext: Logo for rosettasciio
          url: https://hyperspy.org/rosettasciio/
        - img: /images/kikuchipy.svg
          alttext: Logo of kikuchipy
          url: https://kikuchipy.org/en/stable/
        - img: /images/lumispy.svg
          alttext: Logo of lumispy
          url: https://docs.lumispy.org/en/latest/
        - img: /images/atomaplogo.png
          alttext: Logo of atomap
          url: https://atomap.org
        - img: /images/exspy2_white.png
          alttext: Logo of exspy
          url: https://hyperspy.org/exspy/
        - img: /images/holospy2.png
          alttext: Logo of holospy
          url: https://hyperspy.org/holospy/
  footer:
    logo: hyperspy_logo.png
    socialmediatitle: ""
    socialmedia:
      - link: https://app.gitter.im/#/room/#hyperspy_hyperspy:gitter.im
        icon: discourse
      - link: https://github.com/hyperspy/
        icon: github